### PR TITLE
Prefer the locally provided ActivityId

### PR DESCRIPTION
**Pull request by ryangadams**
We've swithered about this back and forth, but the LMS plugin we're
testing against doesn't pass the activityID in the url so we should look
for a local value first.

### CODE REVIEW

**Comment by ryangadams** [comment]
Page level progress wasn't being updated when the course loaded because the stateLoaded event was firing but nothing was listening to it.

**Comment by barry-learningpool** [comment]
+1

**Comment by ryan-lynch** [comment]
+1

**Comment by brian-learningpool** [comment]
+1

**Pull request merged**
